{
 "title": "Ceph",
 "description": "Ceph Cluster overview.\r\n",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Cluster State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_health_status" }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ceph_monitor_quorum_count)" }
   ]
  },
  {
   "title": "Pools",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_pool_available_bytes)"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_cluster_capacity_bytes" }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_cluster_used_bytes" }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((ceph_cluster_available_bytes)/ceph_cluster_capacity_bytes)*100"
    }
   ]
  },
  { "title": "OSD State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "OSDs IN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ceph_osd_in)" }
   ]
  },
  {
   "title": "OSDs OUT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_osd_up) - count(ceph_osd_in)"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ceph_osd_up)" }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_osd_up == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "Average PGs per OSD",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "avg(ceph_osd_pgs)" }
   ]
  },
  {
   "title": "Average OSD Apply Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(ceph_osd_perf_apply_latency_seconds)"
    }
   ]
  },
  {
   "title": "Average OSD Commit Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(ceph_osd_perf_commit_latency_seconds)"
    }
   ]
  },
  { "title": "Recovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "PGs",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    { "expr": "ceph_active_pgs", "legendFormat": "Active" },
    { "expr": "ceph_peering_pgs", "legendFormat": "Peering" },
    { "expr": "ceph_unclean_pgs", "legendFormat": "Unclean" },
    { "expr": "ceph_pg_undersized", "legendFormat": "Undersized" },
    { "expr": "ceph_pg_incomplete", "legendFormat": "Incomplete" },
    { "expr": "ceph_forced_backfill_pgs", "legendFormat": "Forced Backfill" },
    { "expr": "ceph_forced_recovery_pgs", "legendFormat": "Forced Recovery" },
    { "expr": "ceph_backfill_wait_pgs", "legendFormat": "Wait Backfill" },
    { "expr": "ceph_pg_deep", "legendFormat": "Deep" },
    { "expr": "ceph_pg_scrubbing", "legendFormat": "Scrubbing" },
    { "expr": "ceph_pg_recovering", "legendFormat": "Recovering" },
    { "expr": "ceph_down_pgs", "legendFormat": "Down" }
   ]
  },
  {
   "title": "Stuck PGs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "ceph_degraded_pgs", "legendFormat": "Degraded" },
    { "expr": "ceph_stale_pgs", "legendFormat": "Stale" },
    { "expr": "ceph_undersized_pgs", "legendFormat": "Undersized" }
   ]
  },
  { "title": "IO State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "ceph_client_io_write_ops", "legendFormat": "Write" },
    { "expr": "ceph_client_io_read_ops", "legendFormat": "Read" }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "ceph_client_io_write_bytes", "legendFormat": "Write" },
    { "expr": "ceph_client_io_read_bytes", "legendFormat": "Read" }
   ]
  },
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "ceph_cluster_available_bytes", "legendFormat": "Available" },
    { "expr": "ceph_cluster_used_bytes", "legendFormat": "Used" },
    { "expr": "ceph_cluster_capacity_bytes", "legendFormat": "Total Capacity" }
   ]
  },
  {
   "title": "IOPS Reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"10.0.40.7:9100|10.0.40.8:9100|10.0.40.9:9100\",device=~\"sdh|sdi|sdj|sdk\"}[1m])",
     "legendFormat": "{{instance}}{{device}}_Reads"
    }
   ]
  },
  {
   "title": "IOPS Writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"10.0.40.7:9100|10.0.40.8:9100|10.0.40.9:9100\",device=~\"sdh|sdi|sdj|sdk\"}[1m])",
     "legendFormat": "{{instance}}{{device}}_Writes"
    }
   ]
  },
  {
   "title": "Throughtput Reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"10.0.40.7:9100|10.0.40.8:9100|10.0.40.9:9100\",device=~\"sdh|sdi|sdj|sdk\"}[1m])",
     "legendFormat": "{{instance}}{{device}}_Reads"
    }
   ]
  },
  {
   "title": "Throughtput Written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"10.0.40.7:9100|10.0.40.8:9100|10.0.40.9:9100\",device=~\"sdh|sdi|sdj|sdk\"}[1m])",
     "legendFormat": "{{instance}}{{device}}_Written"
    }
   ]
  },
  { "title": "Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Objects in the Cluster",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_cluster_objects", "legendFormat": "Total" }
   ]
  }
 ]
}