{
 "title": "ClickHouse",
 "description": "Clickhouse metrics",
 "tags": [
  "clickhouse",
  "db"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Day Total",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "range",
     "targets": [
      {
       "expr": "sum(clickhouse_inserted_rows_total)"
      }
     ]
    },
    {
     "title": "Day Query",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "format": "none",
     "valueName": "range",
     "targets": [
      { "expr": "sum(clickhouse_query_total)" }
     ]
    },
    {
     "title": "Current Write Speed",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "database": "third_test_query",
       "dateColDataType": "1536969600",
       "dateTimeColDataType": "1537142400",
       "dateTimeType": "TIMESTAMP",
       "expr": "sum(rate(clickhouse_inserted_rows_total[1m]))",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
       "rawQuery": "SELECT     (intDiv(1537142400, 900) * 900) * 1000 as t,     count() FROM third_test_query.ip_log_distributed_05_replica WHERE 1536969600 >= toDate(1537272245) AND 1537142400 >= 1537272245 GROUP BY t ORDER BY t",
       "round": "0s",
       "table": "ip_log_distributed_05_replica"
      }
     ]
    },
    {
     "title": "Current Query Rate",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(clickhouse_query_total[1m])) "
      }
     ]
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "IOPS Writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "iops", "label": "Writes I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sdb\",instance=~\"10.0.40.*\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IOPS Reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "iops", "label": "Reads I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sdb\",instance=~\"10.0.40.*\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU User",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent", "label": "%" }
   ],
   "targets": [
    {
     "expr": "((sum(increase(node_cpu_seconds_total{mode=\"user\",instance=~\"10.0.40.*\"}[1m])) by(instance)) / (sum(increase(node_cpu_seconds_total{instance=~\"10.0.40.*\"}[1m])) by(instance)))*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Iowait",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent", "label": "%" }
   ],
   "targets": [
    {
     "expr": "((sum(irate(node_cpu_seconds_total{mode=\"iowait\",instance=~\"10.0.40.*\"}[1m])) by(instance)) / (sum(irate(node_cpu_seconds_total{instance=~\"10.0.40.*\"}[1m])) by(instance))\n)*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Written Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"10.0.40.*\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"10.0.40.*\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic IN",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "bits", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!~\"em.*|p4p1\",instance=~\"10.0.40.*\"}[5m])*8 ",
     "legendFormat": "{{instance}} {{device}} _in"
    }
   ]
  },
  {
   "title": "Network Traffic Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "bits", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~\"em.*|p4p1\",instance=~\"10.0.40.*\"}[5m])*8 ",
     "legendFormat": "{{instance}} {{device}} _out"
    }
   ]
  },
  {
   "title": "App Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{instance=~\"10.0.40.*\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_SwapCached_bytes - node_memory_Slab_bytes - node_memory_PageTables_bytes - node_memory_VmallocUsed_bytes )  ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"10.0.40.*\"}",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5{instance=~\"10.0.40.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load15",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load15{instance=~\"10.0.40.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Utilization Per Device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdb\",instance=~\"10.0.40.*\"}[5m])*100 ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Total",
     "type": "graph",
     "description": "Number of queries to be interpreted and potentially executed. Does not include queries that failed to parse or were rejected due to AST size limits, quota limits or limits on the number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(clickhouse_query_total[30s]) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "clickhouse_tcp_connection", "legendFormat": "tcp {{instance}}" },
      { "expr": "clickhouse_http_connection", "legendFormat": "http {{instance}}" },
      {
       "expr": "clickhouse_interserver_connection",
       "legendFormat": "interserver {{instance}}"
      }
     ]
    },
    {
     "title": "Query Memory Use",
     "type": "graph",
     "description": "Total amount of memory (bytes) allocated in currently executing queries. Note that some memory allocations may not be accounted.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "clickhouse_memory_tracking", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Select Query",
     "type": "graph",
     "description": "Same as Query, but only for SELECT queries.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(clickhouse_select_query_total[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Query Thread",
     "type": "graph",
     "description": "Number of query processing threads",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "clickhouse_query_thread", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Mark Cache Hits",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(clickhouse_mark_cache_hits_total[60s])",
       "legendFormat": "hits {{instance}}"
      }
     ]
    },
    {
     "title": "Mark Cache Miss",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(clickhouse_mark_cache_misses_total[60s])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Write",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inserted Rows",
     "type": "graph",
     "description": "Number of bytes (uncompressed; for columns as they stored in memory) INSERTed to all tables.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(clickhouse_inserted_rows_total[60s])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Insert Query",
     "type": "graph",
     "description": "Same as Query, but only for INSERT queries.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(clickhouse_insert_query_total[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Inserted Bytes",
     "type": "graph",
     "description": "Number of bytes (uncompressed; for columns as they stored in memory) INSERTed to all tables.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(clickhouse_inserted_bytes_total[60s])/1024",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Delayed Inserts Milliseconds",
     "type": "graph",
     "description": "Number of bytes (uncompressed; for columns as they stored in memory) INSERTed to all tables.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(clickhouse_delayed_inserts_milliseconds_total[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Delayed Inserts",
     "type": "graph",
     "description": "Number of rows INSERTed to all tables.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(clickhouse_delayed_inserts_total[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Merge Numbers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "clickhouse_merge", "legendFormat": "merging parts {{instance}}" }
   ]
  },
  {
   "title": "Merge Rows",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_merged_rows_total[1m])",
     "legendFormat": "merge rows {{instance}}"
    }
   ]
  },
  {
   "title": "Active Parts Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_table_parts_count{database=\"k19_ods\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read/Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "clickhouse_read", "legendFormat": "read  {{instance}}" },
    { "expr": "clickhouse_write", "legendFormat": "write  {{instance}}" }
   ]
  },
  {
   "title": "Slow Read",
   "type": "graph",
   "description": "Number of reads from a file that were slow. This indicate system overload. Thresholds are controlled by read_backoff_* settings.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(clickhouse_slow_read_total[20s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pool Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_background_pool_task",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Compressed Read Buffer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_compressed_read_buffer_bytes_total[60s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Check/Fetch/Send",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "clickhouse_replicated_checks", "legendFormat": "checks  {{instance}}" },
      { "expr": "clickhouse_replicated_fetch", "legendFormat": "fetch  {{instance}}" },
      { "expr": "clickhouse_replicated_send", "legendFormat": "send  {{instance}}" }
     ]
    },
    {
     "title": "ReadOnly Replica",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(clickhouse_readonly_replica)"
      }
     ]
    },
    {
     "title": "Table Replica Leader",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "clickhouse_leader_replica", "legendFormat": "{{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "Distribute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 },
   "collapsed": true,
   "panels": [
    {
     "title": "slow query",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT \r\n    query_start_time AS start, \r\n    multiIf(type = 1, 'start', type = 2, 'success',type = 3, 'errorBeforeStart',type = 4, 'errorProcessing', 'other') AS status, \r\n    query_duration_ms / 1000 AS useSeconds, \r\n    read_rows AS readRows, \r\n    result_rows AS resultRows, \r\n    memory_usage / (1024 * 1024) AS memoryUsageMB, \r\n    query, \r\n    query_id, \r\n    substring(IPv6NumToString(address),8,15) AS queryFromHost\r\nFROM k19_distribute.query_log \r\nWHERE ((start >= $from) AND (start <= $to)) AND (query_duration_ms >=40000)\r\nORDER BY \r\n    useSeconds DESC, \r\n    memoryUsageMB DESC, \r\n    readRows DESC\r\nLIMIT 20",
       "round": "0s"
      }
     ]
    },
    {
     "title": "slow write",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT query_start_time AS start, \r\n    multiIf(type = 1, 'start', type = 2, 'success',type = 3, 'ExceptionBeforeStart',type = 4, 'ExceptionWhileProcessing', 'other') AS status, \r\n    query_duration_ms / 1000 AS useSeconds, \r\n    written_rows AS writeRows, \r\n    written_bytes/1024/1024 AS writtenMB,\r\n    memory_usage / (1024 * 1024) AS memoryUsageMB, \r\n    query, \r\n    query_id, \r\n    substring(IPv6NumToString(address),8,15) AS queryFromHost\r\nFROM k19_distribute.query_log \r\nWHERE ((start >= $from) AND (start <= $to)) AND (query_duration_ms >=30000)\r\nAND writeRows>10000\r\nORDER BY useSeconds DESC,writeRows DESC ,query_start_time DESC\r\nLIMIT 20",
       "round": "0s"
      }
     ]
    }
   ]
  }
 ]
}