{
 "title": "Elasticsearch",
 "description": "Elasticsearch Dashboard for 2.X, 5.X and 6.X",
 "tags": [
  "Elasticsearch",
  "ELK-Infra"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": "{\"find\": \"terms\", \"field\": \"cluster_name.keyword\"}"
   },
   {
    "name": "Node",
    "query": "{\"find\": \"terms\", \"field\": \"name.keyword\", \"query\": \"cluster_name:$Cluster\"}"
   },
   { "name": "nodename", "query": "name.keyword" }
  ]
 },
 "panels": [
  { "title": "Cluster Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "status_code",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Indices",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Active Shards",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "active_shards",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "number_of_nodes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "unassigned_shards",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "initializing_shards",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.store.size_in_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pri. Shards",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "active_primary_shards",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Delayed Un. Shards",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "delayed_unassigned_shards",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Relocating Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "relocating_shards",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "number_of_pending_tasks",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Data Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "number_of_data_nodes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "nodes.process.cpu.percent",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Store Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.store.size_in_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Primary Docs Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.docs.count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "FS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "nodes.fs.total_in_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "nodes.fs.free_in_bytes",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "nodes.jvm.mem.heap_max_in_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "nodes.jvm.mem.heap_used_in_bytes",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Cluster Indices Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Indexing Rate /per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "primaries.indexing.index_total",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "primaries.indexing.index_total",
       "hide": true,
       "id": "1",
       "inlineScript": "_value /60",
       "meta": {},
       "settings": { "script": { "inline": "_value /60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    },
    {
     "alias": "total.indexing.index_total",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "total.indexing.index_total",
       "hide": true,
       "id": "1",
       "inlineScript": "_value /60",
       "meta": {},
       "settings": { "script": { "inline": "_value /60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Indexing Latency /per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "primaries.indexing.index_time",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "primaries.indexing.index_time_in_millis",
       "hide": true,
       "id": "1",
       "inlineScript": "_value /60",
       "meta": {},
       "settings": {
        "missing": null,
        "script": { "inline": "_value /60" }
       },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    },
    {
     "alias": "total.indexing.index_time",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "total.indexing.index_time_in_millis",
       "hide": true,
       "id": "1",
       "inlineScript": "_value /60",
       "meta": {},
       "settings": { "script": { "inline": "_value /60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Merges /per min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "primaries.merges.total",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "primaries.merges.total",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    },
    {
     "alias": "total.merges.total",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "total.merges.total",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Merges Latency /per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "primaries.merges.total_time_in_millis",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "primaries.merges.total_time_in_millis",
       "hide": true,
       "id": "1",
       "inlineScript": "_value /60",
       "meta": {},
       "settings": { "script": { "inline": "_value /60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    },
    {
     "alias": "total.merges.total_time_in_millis",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "total.merges.total_time_in_millis",
       "hide": true,
       "id": "1",
       "inlineScript": "_value /60",
       "meta": {},
       "settings": { "script": { "inline": "_value /60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Segments Memory / Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "primaries.segments.doc_values_memory_in_bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "primaries.segments.fixed_bit_set_memory_in_bytes",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "primaries.segments.index_writer_max_memory_in_bytes",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "primaries.segments.index_writer_memory_in_bytes",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "primaries.segments.memory_in_bytes",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "primaries.segments.norms_memory_in_bytes",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "primaries.segments.stored_fields_memory_in_bytes",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "primaries.segments.terms_memory_in_bytes",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "primaries.segments.version_map_memory_in_bytes",
       "id": "10",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.segments.count",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Search Rate / Latency  /per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "primaries.search.query_time",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "primaries.search.query_time_in_millis",
       "hide": true,
       "id": "1",
       "inlineScript": "_value /60",
       "meta": {},
       "settings": { "script": { "inline": "_value /60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    },
    {
     "alias": "primaries.search.query_total",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "primaries.search.query_total",
       "hide": true,
       "id": "1",
       "inlineScript": "_value /60",
       "meta": {},
       "settings": { "script": { "inline": "_value /60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Field Data Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "primaries.fielddata.memory_size_in_bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cluster_name:$Cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Cluster Addtional", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "ES Thread",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "measurement": "es_thread",
     "query": "SELECT \"active\" FROM \"es_thread\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "host" ], "type": "field" }
      ],
      [
       { "params": [ "name" ], "type": "field" }
      ],
      [
       { "params": [ "active" ], "type": "field" }
      ],
      [
       { "params": [ "queue" ], "type": "field" }
      ],
      [
       { "params": [ "rejected" ], "type": "field" }
      ],
      [
       { "params": [ "completed" ], "type": "field" }
      ],
      [
       { "params": [ "queue_size" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=", "value": "172.24.9.49" }
     ]
    }
   ]
  },
  { "title": "Node OS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "FS Free",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 49 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fs.total.available_in_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 49 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "os.cpu.percent",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "process.cpu.percent",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "os.cpu.load_average.1m",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "os.cpu.load_average.5m",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "os.mem.total_in_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "os.mem.used_in_bytes",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "os.swap.total_in_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "os.swap.used_in_bytes",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Fs.Io_Stats.Total Read /per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-Read",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fs.io_stats.total.read_kilobytes",
       "hide": true,
       "id": "1",
       "inlineScript": "_value /60",
       "meta": {},
       "settings": { "script": { "inline": "_value /60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Fs.Io_Stats.Total Write /per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-Write",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fs.io_stats.total.write_kilobytes",
       "hide": true,
       "id": "1",
       "inlineScript": "_value /60",
       "meta": {},
       "settings": { "script": { "inline": "_value /60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Transport /per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-RX",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "transport.rx_size_in_bytes",
       "hide": true,
       "id": "1",
       "inlineScript": "_value /60",
       "meta": {},
       "settings": { "script": { "inline": "_value /60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{$nodename}}-TX",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "transport.tx_size_in_bytes",
       "hide": true,
       "id": "1",
       "inlineScript": "_value /60",
       "meta": {},
       "settings": { "script": { "inline": "_value /60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Node Stats Indices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Field Data & Breakers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "breakers.fielddata.estimated_size_in_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "indices.fielddata.memory_size_in_bytes",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "breakers.parent.estimated_size_in_bytes",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "breakers.request.estimated_size_in_bytes",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "breakers.in_flight_requests.estimated_size_in_bytes",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HTTP Open",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-requests",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.total_opened",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Indices docs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.docs.count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "indices.docs.deleted",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Indexing Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-indexing.index_time",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.indexing.index_time_in_millis",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Indexing Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-indexing.index_total",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.indexing.index_total",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Merges Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-merges",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.merges.total",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{$nodename}}-total_docs",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.merges.total_docs",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Merges.Total_Size_In_Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-indices.merges.total_size",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.merges.total_size_in_bytes",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Merges Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 69 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-indices.merges.total_throttled_time",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.merges.total_throttled_time_in_millis",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{$nodename}}-indices.merges.total_time_in_millis",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.merges.total_time_in_millis",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Indices Search",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-search.query_time",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.search.query_time_in_millis",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{$nodename}}-search.query_total",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.search.query_total",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.segments.count",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Segments Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "8",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.segments.doc_values_memory_in_bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "indices.segments.index_writer_memory_in_bytes",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "indices.segments.memory_in_bytes",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "indices.segments.stored_fields_memory_in_bytes",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "indices.segments.terms_memory_in_bytes",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "indices.segments.version_map_memory_in_bytes",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Translog",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.translog.operations",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices.translog.size_in_bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Node JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 84 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.uptime_in_millis",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 84 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.mem.heap_used_percent",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 84 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.mem.heap_max_in_bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "jvm.mem.heap_used_in_bytes",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Jvm.Gc.Collectors.Young",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-young.collection_count",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.gc.collectors.young.collection_count",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{$nodename}}-young.collection_time",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.gc.collectors.young.collection_time_in_millis",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Jvm.Gc.Collectors.Old",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-old.collection",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.gc.collectors.old.collection_count",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{$nodename}}-old.collection_time",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.gc.collectors.old.collection_time_in_millis",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OLD",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.mem.pools.old.peak_max_in_bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "jvm.mem.pools.old.peak_used_in_bytes",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Survivor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 90 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "5",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.mem.pools.survivor.max_in_bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "jvm.mem.pools.survivor.peak_used_in_bytes",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "jvm.mem.pools.survivor.used_in_bytes",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Young",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 90 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "5",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.mem.pools.young.max_in_bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "jvm.mem.pools.young.peak_used_in_bytes",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "jvm.mem.pools.young.used_in_bytes",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.threads.count",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "jvm.threads.peak_count",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 90 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{$nodename}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.mem.non_heap_committed_in_bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "jvm.mem.non_heap_used_in_bytes",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:$Node",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}