{
 "title": "HBase",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "MemStore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MemStore Size Total",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "sum(hadoop_hbase_memstoresize)" }
   ]
  },
  {
   "title": "MemStore Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "hadoop_hbase_memstoresize", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "GCTimeMillis Concurrent MarkSweep",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hadoop_hbase_gctimemillisconcurrentmarksweep",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Gc TimeMillis",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "hadoop_hbase_gctimemillis", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Gc TimeMillis ParNew",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hadoop_hbase_gctimemillisparnew",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Region Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 33 },
   "targets": [
    { "expr": "hadoop_hbase_regioncount", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HlogFile Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hadoop_hbase_hlogfilecount", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "ReadRequest Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "hadoop_hbase_readrequestcount", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "WriteRequest Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "hadoop_hbase_writerequestcount", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "StoreFile Count Total",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 61 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(hadoop_hbase_storefilecount)"
    }
   ]
  },
  {
   "title": "StoreFile Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 9, "y": 61 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "hadoop_hbase_storefilecount", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "MemHeap UsedM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "hadoop_hbase_memheapusedm", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "BlockCache Miss Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_hbase_blockcachemisscount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BlockCache Hit Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_hbase_blockcachehitcount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Percent Files Local",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "hadoop_hbase_percentfileslocal", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "SlowGet Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "hadoop_hbase_slowgetcount", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "UpdatesBlocked Time Total",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 112 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(hadoop_hbase_updatesblockedtime)"
    }
   ]
  },
  {
   "title": "UpdatesBlocked Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 9, "y": 112 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hadoop_hbase_updatesblockedtime",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Compacted Cells Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_hbase_majorcompactedcellscount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Flushed Cells Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "hadoop_hbase_flushedcellscount", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "FlushQueue Length",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hadoop_hbase_flushqueuelength", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CompactionQueue Length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hbase_compactionqueuelength",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SmallCompactionQueue Length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hbase_smallcompactionqueuelength",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LargeCompactionQueue Length",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hbase_largecompactionqueuelength",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}