{
 "title": "OSS",
 "description": "ntc_oss_monitor_log流量和TPS监控",
 "tags": [ "k19_ods" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "File Type Size Ratio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "database": "k19_ods",
     "dateColDataType": "recvdate",
     "dateTimeColDataType": "recvtime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    1,\n    category,\n    sum(filesize)\nFROM k19_ods.ntc_oss_monitor_log\nWHERE\n    dealtime >= $from * 1000\n    and dealtime <= $to * 1000\nGROUP BY category",
     "rawQuery": "SELECT     1,     category,     sum(filesize) FROM k19_ods.ntc_oss_monitor_log WHERE     recvtime >= 1542424011 * 1000     and recvtime <= 1542510416 * 1000 GROUP BY category",
     "round": "0s",
     "table": "ntc_oss_monitor_log"
    }
   ]
  },
  {
   "title": "Number of Data Types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    1,\n    category,\n    count(1) \nFROM k19_ods.ntc_oss_monitor_log\nWHERE\n    dealtime >= $from * 1000\n    and dealtime <= $to * 1000\nGROUP BY category",
     "rawQuery": "SELECT     1,     category,     count(1)  FROM k19_ods.ntc_oss_monitor_log WHERE     recvtime >= 1542424011 * 1000     and recvtime <= 1542510416 * 1000 GROUP BY category",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Dzn Server Flow",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "k19_ods",
     "dateColDataType": "recvdate",
     "dateTimeColDataType": "recvtime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    t,\r\n    groupArray((serverIp, s)) as groupArr\r\nFROM\r\n(\r\n    SELECT\r\n        (intDiv(dealtime, 60000) * 60000)  as t,\r\n        serverIp,\r\n        sum(filesize) s\r\n    FROM k19_ods.ntc_oss_monitor_log\r\n    WHERE\r\n        dealtime >= $from * 1000\r\n        AND dealtime < $to * 1000\r\n    GROUP BY\r\n        t,\r\n        serverIp\r\n    ORDER BY\r\n        t,\r\n        serverIp\r\n)\r\nGROUP BY t\r\nORDER BY t",
     "rawQuery": "SELECT     t,     groupArray((server, s)) as groupArr FROM (     SELECT         (intDiv(recvtime, 60000) * 60000)  as t,         server,         sum(filesize) s     FROM k19_ods.ntc_oss_monitor_log     WHERE         recvtime >= 1542424011 * 1000         AND recvtime < 1542510416 * 1000     GROUP BY         t,         server     ORDER BY         t,         server ) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "ntc_oss_monitor_log"
    }
   ]
  },
  {
   "title": "Dzn Server TPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "k19_ods",
     "dateColDataType": "recvdate",
     "dateTimeColDataType": "recvtime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    t,\r\n    groupArray((serverIp, c)) as groupArr\r\nFROM\r\n(\r\n    SELECT\r\n        (intDiv(dealtime, 60000) * 60000) as t,\r\n        serverIp,\r\n        count(1) c\r\n    FROM k19_ods.ntc_oss_monitor_log\r\n    WHERE\r\n        dealtime >= $from * 1000\r\n        AND dealtime < $to * 1000\r\n    GROUP BY\r\n        t,\r\n        serverIp\r\n    ORDER BY\r\n        t,\r\n        serverIp\r\n)\r\nGROUP BY t\r\nORDER BY t",
     "rawQuery": "SELECT     t,     groupArray((server, c)) as groupArr FROM (     SELECT         (intDiv(recvtime, 60000) * 60000) as t,         server,         count(1) c     FROM k19_ods.ntc_oss_monitor_log     WHERE         recvtime >= 1542424011 * 1000         AND recvtime < 1542510416 * 1000     GROUP BY         t,         server     ORDER BY         t,         server ) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "ntc_oss_monitor_log"
    }
   ]
  },
  {
   "title": "Dzn FileType Flow",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "k19_ods",
     "dateColDataType": "recvdate",
     "dateTimeColDataType": "recvtime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    t,\r\n    groupArray((category, s)) as groupArr\r\nFROM\r\n(\r\n    SELECT\r\n        (intDiv(dealtime, 60000) * 60000)  as t,\r\n        category,\r\n        sum(filesize) s\r\n    FROM k19_ods.ntc_oss_monitor_log\r\n    WHERE\r\n        dealtime BETWEEN $from * 1000\r\n        AND $to * 1000\r\n    GROUP BY\r\n        t,\r\n        category\r\n    ORDER BY\r\n        t,\r\n        category\r\n)\r\nGROUP BY t\r\nORDER BY t",
     "rawQuery": "SELECT     t,     groupArray((category, s)) as groupArr FROM (     SELECT         (intDiv(recvtime, 60000) * 60000)  as t,         category,         sum(filesize) s     FROM k19_ods.ntc_oss_monitor_log     WHERE         recvtime BETWEEN 1542424011 * 1000         AND 1542510416 * 1000     GROUP BY         t,         category     ORDER BY         t,         category ) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "ntc_oss_monitor_log"
    }
   ]
  },
  {
   "title": "Dzn FileType TPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateColDataType": "recvdate",
     "dateTimeColDataType": "recvtime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    t,\n    groupArray((category, c)) as groupArr\nFROM\n(\n    SELECT\n        (intDiv(dealtime, 60000) * 60000)  as t,\n        category,\n        count(*) c\n    FROM k19_ods.ntc_oss_monitor_log\n    WHERE\n        dealtime BETWEEN $from * 1000\n        AND $to * 1000\n    GROUP BY\n        t,\n        category\n    ORDER BY\n        t,\n        category\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     t,     groupArray((category, c)) as groupArr FROM (     SELECT         (intDiv(recvtime, 60000) * 60000)  as t,         category,         count(*) c     FROM k19_ods.ntc_oss_monitor_log     WHERE         recvtime BETWEEN 1542424011 * 1000         AND 1542510416 * 1000     GROUP BY         t,         category     ORDER BY         t,         category ) GROUP BY t ORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "FileName TopN",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    now(),\n    filename,\n    count(1) as num\nFROM k19_ods.ntc_oss_monitor_log\nWHERE\n    dealtime >= $from * 1000\n    and dealtime < $to * 1000\nGROUP BY filename\nORDER BY num desc\nLIMIT 3",
     "rawQuery": "SELECT     now(),     filename,     count(1) as num FROM k19_ods.ntc_oss_monitor_log WHERE     recvtime >= 1542424011 * 1000     and recvtime < 1542510416 * 1000 GROUP BY filename ORDER BY num desc LIMIT 3",
     "round": "0s"
    }
   ]
  },
  {
   "title": "CfgId TopN",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    now(),\n    cfgid,\n    count(1) as num\nFROM k19_ods.ntc_oss_monitor_log\nWHERE\n    dealtime >= $from * 1000\n    and dealtime < $to * 1000\nGROUP BY cfgid\nORDER BY num desc\nLIMIT 3",
     "rawQuery": "SELECT     now(),     cfgid,     count(1) as num FROM k19_ods.ntc_oss_monitor_log WHERE     recvtime >= 1542424011 * 1000     and recvtime < 1542510416 * 1000 GROUP BY cfgid ORDER BY num desc LIMIT 3",
     "round": "0s"
    }
   ]
  }
 ]
}