{
 "title": "Tomcat",
 "description": "https://github.com/prometheus/jmx_exporter",
 "tags": [
  "JVM",
  "tomcat"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Threads Deadlocked",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "jvm_threads_deadlocked{group=\"tomcat\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UP State",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "up{group=\"tomcat\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Heap Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (jvm_memory_bytes_used{area=\"heap\",job=\"tomcat_metric\",group=\"tomcat\"}) by (instance)",
     "legendFormat": "{{instance}}_used"
    },
    {
     "expr": "sum (jvm_memory_bytes_committed{area=\"heap\",job=\"tomcat_metric\",group=\"tomcat\"}) by (instance)",
     "legendFormat": "{{instance}}_committed"
    }
   ]
  },
  {
   "title": "Mem Committed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (jvm_memory_bytes_used{area=\"nonheap\",job=\"tomcat_metric\",group=\"tomcat\"}) by (instance)",
     "legendFormat": "{{instance}}_used"
    },
    {
     "expr": "sum (jvm_memory_bytes_committed{area=\"nonheap\",job=\"tomcat_metric\",group=\"tomcat\"}) by (instance)",
     "legendFormat": "{{instance}}_committed"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (jvm_memory_pool_bytes_used{pool=\"Code Cache\",job=\"tomcat_metric\",group=\"tomcat\"}) by (instance)",
     "legendFormat": "{{instance}}_used"
    },
    {
     "expr": "sum (jvm_memory_pool_bytes_committed{pool=\"Code Cache\",job=\"tomcat_metric\",group=\"tomcat\"}) by (instance)",
     "legendFormat": "{{instance}}_committed"
    }
   ]
  },
  {
   "title": "threads",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"tomcat_metric\",group=\"tomcat\"}",
     "legendFormat": "{{instance}} Current thread connection number"
    },
    {
     "expr": "jvm_threads_started_total{job=\"tomcat_metric\",group=\"tomcat\"}",
     "legendFormat": "{{instance}} Total number of threads"
    },
    {
     "expr": "jvm_threads_peak{job=\"tomcat_metric\",group=\"tomcat\"}",
     "legendFormat": "{{instance}} Thread peak"
    },
    {
     "expr": "jvm_threads_deadlocked_monitor{job=\"tomcat_metric\",group=\"tomcat\"}",
     "legendFormat": "{{instance}} deadlocked_monitor"
    }
   ]
  },
  {
   "title": "Classes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{job=\"tomcat_metric\",group=\"tomcat\"}",
     "legendFormat": "{{instance}} Classes that have been loaded"
    },
    {
     "expr": "jvm_classes_loaded_total{job=\"tomcat_metric\",group=\"tomcat\"}",
     "legendFormat": "{{instance}} The sum of the load classes"
    },
    {
     "expr": "jvm_classes_unloaded_total{job=\"tomcat_metric\",group=\"tomcat\"}",
     "legendFormat": "{{instance}} class that has been uninstalled"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(tomcat_bytesreceived_total{protocol=\"http-apr\",group=\"tomcat\"}[10m]))",
     "legendFormat": "input"
    },
    {
     "expr": "sum(irate(tomcat_bytessent_total{protocol=\"http-apr\",group=\"tomcat\"}[10m]))",
     "legendFormat": "output"
    }
   ]
  },
  { "title": "Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Errorcount Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_errorcount_total{group=\"tomcat\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Maxtime Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_maxtime_total{group=\"tomcat\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requestcount Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_requestcount_total{group=\"tomcat\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Servlet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Servlet Requestcount Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tomcat_servlet_requestcount_total{module=\"localhost/\",servlet=\"dispatcherServlet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Servlet Errorcount Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tomcat_servlet_errorcount_total{module=\"localhost/\",servlet=\"dispatcherServlet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Servlet Processingtime Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tomcat_servlet_processingtime_total{module=\"localhost/\",servlet=\"dispatcherServlet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Servlet Maxtime Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tomcat_servlet_maxtime_total{module=\"localhost/\",servlet=\"dispatcherServlet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}