#kafka
kafka:
  kafkaTopic: "K19-ASTANA-DM-MONITOR-LOG"
  kafkaBrokerList: "{{monKafkaBrokerList}}"
  offSet: "latest"
  groupId: "k19_product_dm_monitor_log"
  autoCommit: false

spark:
  appName: "dm_monitor_application"
  intervalTime: 5

clickHouse:
  insertBlukSize: 30000
  insertFormat: "TabSeparated"
  ipPort: "{{clickhouseIpPort}}"
  database: "k19_monitor"
  table: "k19_dm_log_monitor"
  fields: "time_string,time_second,ip,region,action,file_name,file_size,uuid"
  intervalTime: 3
  connRetryCount: 3
  failConnRejoinInterval: 60
  userName: {{ck_username}}
  password: {{ck_password}}
  timeSwitch: true

# for monitor
monitor:
  offSwitch: true
  errorMessageTopic: "K19-TEST-EXCEPTION-MESSAGE"
  kafkaBrokerList: "{{monKafkaBrokerList}}"
  exceptionSize: 10000
  flushSwitch: false
logLevel: "INFO"
region: "ALA"
separateSign: "comma"
