---
# tasks file for ssh_single
- name: generating public/private rsa key pair 
  shell: ssh-keygen -t rsa -b 2048 -N '' -f /root/.ssh/id_rsa
  run_once: true
  delegate_to: "{{jump_brother}}"
- name: ssh-copy
  authorized_key: user=root key="{{ lookup('file', '/root/.ssh/id_rsa.pub') }}" state=present


