---
# tasks file for ssh_single
- name: generating public/private rsa key pair 
  shell: ssh-keygen -t rsa -b 2048 -N '' -f /root/.ssh/id_rsa
  run_once: true
  delegate_to: "{{jump_brother}}"
- name: view id_rsa.pub 
  shell: cat /root/.ssh/id_rsa.pub
  register: sshinfo
  run_once: true
  delegate_to: "{{jump_brother}}"
- set_fact: sshpub={{sshinfo.stdout}}
- name: add ssh record
  shell: echo {{sshpub}} >> /root/.ssh/authorized_keys
