---

- name: modify zabbix-agent.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: 'Server={{ server_ip }}'
    line: 'Server={{ proxy_ip }}'
    backrefs: yes
- name: modify zabbix-agent.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: 'ServerActive={{ server_ip }}'
    line: 'ServerActive={{ proxy_ip }}'
    backrefs: yes

- name: systemctl restart zabbix-agent
  shell: systemctl restart zabbix-agent

- name: Check if zabbix-agent is accessible
  wait_for:
    port: 10050
    state: started
    delay: 10
    timeout: 15
    connect_timeout: 5

