management:
  security:
    enabled: false
server:
  port: {{service_port}}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048
dubbo: 
  protocol: zookeeper
  address: {{register_zk}}
  isRegister: true
spring: 
  datasource: 
    mysql:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://{{mysql_addr}}/onto_config_stg?characterEncoding=utf8
      username: {{mysql_user}}
      password: {{mysql_password}}
      filters: stat, wall, log4j，去掉后监控界面sql将无法统计,'wall'用于防火墙
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
    #上传的CSV文件存储到MySQL库中：要有有容量限制
    file:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://{{mysql_addr}}/upload?characterEncoding=utf8
      username: {{mysql_user}}
      password: {{mysql_password}}
      uploadPath: {{deploy_path}}/config-service/upload/
      filters: stat, wall, log4j，去掉后监控界面sql将无法统计,'wall'用于防火墙
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
    #当前是为了删除es数据 deprecated todo移到单独的工具里
    es:
      index_prefix: atom_v1
      hosts: {{es_hosts}}
      port: {{es_port}}
      clusterName: {{es_clustername}}
      time_field: create_time
      time_format: yyyy-MM-dd HH:mm:ss
  page:
    size: 50
  #上传csv文件
  http:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
#配置文件导入导出：deprecated
confUpload:
  path: {{deploy_path}}/config-service/upload-xml/
systemmanager:
  config:
    isRun: false
    sysServer: {{systemmanager_addr}}
    cookie_key: tokenId
